<?php

/**
 * BaseRlmGoodDeal
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $partner_id
 * @property string $title
 * @property string $content
 * @property boolean $homepage
 * @property RlmPartner $RlmPartner
 * 
 * @method integer     getPartnerId()  Returns the current record's "partner_id" value
 * @method string      getTitle()      Returns the current record's "title" value
 * @method string      getContent()    Returns the current record's "content" value
 * @method boolean     getHomepage()   Returns the current record's "homepage" value
 * @method RlmPartner  getRlmPartner() Returns the current record's "RlmPartner" value
 * @method RlmGoodDeal setPartnerId()  Sets the current record's "partner_id" value
 * @method RlmGoodDeal setTitle()      Sets the current record's "title" value
 * @method RlmGoodDeal setContent()    Sets the current record's "content" value
 * @method RlmGoodDeal setHomepage()   Sets the current record's "homepage" value
 * @method RlmGoodDeal setRlmPartner() Sets the current record's "RlmPartner" value
 * 
 * @package    rlm
 * @subpackage model
 * @author     stef
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseRlmGoodDeal extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('rlm_good_deal');
        $this->hasColumn('partner_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('title', 'string', 250, array(
             'type' => 'string',
             'length' => 250,
             ));
        $this->hasColumn('content', 'string', 4000, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 4000,
             ));
        $this->hasColumn('homepage', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => true,
             'default' => 1,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('RlmPartner', array(
             'local' => 'partner_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}