<?php

/**
 * BaseRlmNews
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property enum $type
 * @property string $title
 * @property string $content
 * @property string $link
 * 
 * @method enum    getType()    Returns the current record's "type" value
 * @method string  getTitle()   Returns the current record's "title" value
 * @method string  getContent() Returns the current record's "content" value
 * @method string  getLink()    Returns the current record's "link" value
 * @method RlmNews setType()    Sets the current record's "type" value
 * @method RlmNews setTitle()   Sets the current record's "title" value
 * @method RlmNews setContent() Sets the current record's "content" value
 * @method RlmNews setLink()    Sets the current record's "link" value
 * 
 * @package    rlm
 * @subpackage model
 * @author     stef
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseRlmNews extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('rlm_news');
        $this->hasColumn('type', 'enum', null, array(
             'type' => 'enum',
             'values' => 
             array(
              0 => 'Site',
              1 => 'Nouveau Partenaire',
              2 => 'Nouveau Bon Plan',
             ),
             ));
        $this->hasColumn('title', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('content', 'string', 4000, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 4000,
             ));
        $this->hasColumn('link', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}