<?php

/**
 * BaseRlmContact
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $first_name
 * @property string $last_name
 * @property string $address
 * @property string $phone_number
 * @property string $email_address
 * @property string $question
 * 
 * @method string     getFirstName()     Returns the current record's "first_name" value
 * @method string     getLastName()      Returns the current record's "last_name" value
 * @method string     getAddress()       Returns the current record's "address" value
 * @method string     getPhoneNumber()   Returns the current record's "phone_number" value
 * @method string     getEmailAddress()  Returns the current record's "email_address" value
 * @method string     getQuestion()      Returns the current record's "question" value
 * @method RlmContact setFirstName()     Sets the current record's "first_name" value
 * @method RlmContact setLastName()      Sets the current record's "last_name" value
 * @method RlmContact setAddress()       Sets the current record's "address" value
 * @method RlmContact setPhoneNumber()   Sets the current record's "phone_number" value
 * @method RlmContact setEmailAddress()  Sets the current record's "email_address" value
 * @method RlmContact setQuestion()      Sets the current record's "question" value
 * 
 * @package    rlm
 * @subpackage model
 * @author     stef
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseRlmContact extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('rlm_contact');
        $this->hasColumn('first_name', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('last_name', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('address', 'string', 2000, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 2000,
             ));
        $this->hasColumn('phone_number', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('email_address', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'unique' => true,
             'length' => 255,
             ));
        $this->hasColumn('question', 'string', 10000, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 10000,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}