<?php

/**
 * RlmCategoryTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class RlmCategoryTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object RlmCategoryTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('RlmCategory');
    }
}