<?php

/**
 * RlmGoodDealTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class RlmGoodDealTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object RlmGoodDealTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('RlmGoodDeal');
    }


    public function getGoodDealHomepage($max = 3){
        $query = Doctrine_Query::create()
        ->from('RlmGoodDeal gd')
        ->addWhere('gd.homepage = ?',1)
        ->addOrderBy('gd.created_at DESC')
        ->limit($max);

    	return $query->execute();
    }

    public function searchGoodDeals(sfWebRequest $request){


        $query = Doctrine_Query::create()
        ->from('RlmGoodDeal gd')
        ->leftJoin('gd.RlmPartner p')
        ->addWhere('p.name LIKE "%'.$request->getParameter('recherche').'%"');
        
        
        if($request->getParameter('type_p') != "Thématiques" && $request->getParameter('type_p') != "")
           $query->addWhere('p.type ="'.$request->getParameter('type_p').'"');

        if($request->getParameter('type_bp') != "Type d'offre" && $request->getParameter('type_bp') != "")
           $query->addWhere('gd.type ="'.$request->getParameter('type_bp').'"');



    	return $query->execute();
    }

}