<?php

/**
 * RlmNewsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class RlmNewsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object RlmNewsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('RlmNews');
    }

    public function getNewsList($max = 4){
        $query = Doctrine_Query::create()
        ->from('RlmNews n')
        ->addOrderBy('n.created_at DESC')
        ->limit($max);

    	return $query->execute();
    }
}