<?php

/**
 * RlmPartner
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    rlm
 * @subpackage model
 * @author     stef
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class RlmPartner extends BaseRlmPartner
{
    public function setUp()
    {
        parent::setUp();
        $this->hasMany('RlmGoodDeal as RlmGoodDeal', array(
             'local' => 'id',
             'foreign' => 'partner_id'));
    }
}
