<?php

/**
 * RlmPartnerTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class RlmPartnerTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object RlmPartnerTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('RlmPartner');
    }

    public function getWithGoodDeals()
    {
        $q = $this->createQuery('p')
        ->leftJoin('p.RlmGoodDeal gd');
        
        return $q->execute();
    }


}